### ISSUE TITLE
Doesn't work for me

### ISSUE THREAD

**Issue by Itay080** [cuevavirus/QuickVolume#1]
Hi, thanks for the plugin!
But it doesn't seem to work for me. I use 3.68 with h-encore. Quick Power works just fine. I've tried uninstalling it to see if they conflict each other but it still doesn't work.
My plugins list is:
**kernel**
kuio
storagemgr
reF00D
ds4vita
adrenaline_kernel
PSVshell

**main**
henkaku
shellbat
download_enabler
quick_volume

**Comment by cuevavirus** [comment]
Can you attach the actual config.txt and show a picture of where you have placed the file?

**Comment by Itay080** [comment]
Sure thing :)
Here's the config.txt
[config.txt](https://github.com/cuevavirus/QuickVolume/files/4083826/config.txt)
I've placed the file in ur0:tai

**Comment by cuevavirus** [comment]
Config looks fine to me. Can you please try this build and upload the log from `ux0:quick_volume.txt`?
Make sure to open the quick menu at least once.

[quick_volume.zip](https://github.com/cuevavirus/QuickVolume/files/4084751/quick_volume.zip)

**Comment by Itay080** [comment]
[quick_volume.txt](https://github.com/cuevavirus/QuickVolume/files/4084916/quick_volume.txt)
There you go

**Comment by cuevavirus** [comment]
I can confirm this problem using hencore on 3.65. However, works fine with enso. Taihen has problem hooking imports of SceShell for some reason. I'll look for a workaround.

**Comment by cuevavirus** [comment]
Fixed in 7cdd59d6c4a9b89a50961af82175e17d8aaa4c5b and released v1.2.1.
